# netlify.toml

# Build settings
[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html for SPA support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enforce correct MIME type for JavaScript files
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
